<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.15" />
		<PackageReference Include="Grpc.AspNetCore" Version="2.57.0" />
		<PackageReference Include="Grpc.Tools" Version="2.80.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\PersonService.Application\PersonService.Application.csproj" />
		<ProjectReference Include="..\PersonService.Contracts\PersonService.Contracts.csproj" />
		<ProjectReference Include="..\PersonService.Infrastructure\PersonService.Infrastructure.csproj" />
	</ItemGroup>

</Project>

